version: '3.9'

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    ports:
      - '5431:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_BASE}"

    volumes:
      - postgres_data:/var/lib/postgresql/data/